extern void wipeMemory(void* start, int size);
extern void tagKong(int kong);
extern void cancelMusic(int song, int unk0);
extern void clearTagSlide(void* actor);
extern void playAnimation(void* actor, int local_animation);
extern void handleAnimation(void* actor);
extern int getWorld(int map);
extern int* displayText(int* dl, int style, int x, int y, char* str, int params);
extern int getStringWidth(int style, char* str);

extern PlayerInventory PlayerItems[4];
extern PlayerData* Player;
extern SwapStruct* SwapObject;
extern float LZFadeoutProgress;
extern unsigned char CutsceneActive;
extern unsigned char ModelTwoTouchCount;
extern int CurrentMap;
extern unsigned char MapState;
extern short LoadedActorCount;
extern LoadedActor LoadedActorArray[64];
extern unsigned char TBVoidByte;
extern unsigned char Character;
extern hudData* HUD;
extern Controller ControllerInput;
extern int ObjectTimer;
extern short DKTVTimer;
extern DemoStruct DemoMaps[3];